name: Remote SSH Command
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export PATH="/root/.local/share/pnpm:/root/.nvm/versions/node/v20.19.1/bin:$PATH"
            cd /var/www/devblog
            git pull origin main
            composer install --no-dev --optimize-autoloader --no-interaction
            php artisan migrate --force
            /root/.local/share/pnpm/pnpm install
            /root/.local/share/pnpm/pnpm build
            php artisan migrate --force
